apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      components: backend-conv-app
  template:
    metadata:
      labels:
        components: backend-conv-app
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api:latest
          imagePullPolicy: Always  # IfNotPresent  Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: conv-api-secret
                  key: DATABASE_URL
          resources:
            limits:
              memory: "800Mi"
              cpu: "1000m"
          volumeMounts:
            - name: api-data
              mountPath: /var/lib/api/
              subPath: api
      volumes:
        - name: api-data
          persistentVolumeClaim:
            claimName: api-pvc
